spring.application.name=user-service
server.servlet.context-path=/users

server.port=9020

# PostgreSQL datasource (for DBeaver: use same host, port, database, username, password)
spring.datasource.url=jdbc:postgresql://localhost:5432/userDb 
spring.datasource.username=postgres
spring.datasource.password=Snehil@208001
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey=2bjb234jbu23b4j2b4b234jb23j4b32j4bjk32b4jb324jk23bjk4b32jkb432jb423

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true